name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "image tag prefix"
        default: "rc"
        required: true
jobs:
  _:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@62ddfc16c29b86028b855f5b999329c6abca4207
      - name: Prepare
        id: prep
        env:
          GIT_REF: ${{ github.ref }}
          GIT_SHA: ${{ github.sha }}
          RELEASE_CANDIDATE_PREFIX: ${{ github.event.inputs.tag }}
        run: |
          VERSION="${RELEASE_CANDIDATE_PREFIX}-${GIT_SHA::8}"
          if [[ $GIT_REF == refs/tags/* ]]; then
            VERSION=${GIT_REF/refs\/tags\//}
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Generate release artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CONTROLLER: ${{ github.event.repository.name }}
        run: |
          mkdir -p config/release
          kustomize build ./config/crd > ./config/release/${CONTROLLER}.crds.yaml
          kustomize build ./config/manager > ./config/release/${CONTROLLER}.deployment.yaml
      - name: Create release
        id: run-goreleaser
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
